config/routes.rb
Rails.application.routes.draw do
  get 'excerpts/new'
  get 'signs/new'
  get 'sources/new'
  get 'projects/new'
  get 'tags/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, except: [:new]
  resources :sources, except: [:new]
  resources :tags, except: [:new]
  resources :signs, except: [:show]
  resources :excerpts
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is a note taking app for source-based content creators.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact nicolasgkruk at gmail dot com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Guide") %>
<!DOCTYPE html>
<h1>How to use Skiltr</h1>
<ol>
  <li>Add <%= link_to "excerpts", excerpts_new_path %> (each of them extracted from a source: book, article, blog post, etc.).</li>
  <li>Search through your <%= link_to "excerpts", excerpts_path %> and select one or more that you wish to use to create a sign from. You could also create a sign <%= link_to "directly", signs_new_path %>, without choosing excerpts from the excerpts list, but it might be cumbersome, especially when/if you have a decent amount of excerpts already.</li>
  <li>Add a sign comprised of that/those excerpts. Each sign is made of a personal comment which you craft from a series of excerpts. Every sign is attached to a project (more generally a written piece: book, blog post, dissertation, screenplay, whatever). Hence, a project is comprised of multiple signs.</li>
  <li>Search through your <%= link_to "signs", signs_path %> and use them to compose ideas for your project.</li>
</ol>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Skiltr</h1>

  <h2>
    This is the home page for Skiltr:
    note taking for content creators
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>