config/routes.rb
Rails.application.routes.draw do
  get 'excerpts/new'
  get 'signs/new'
  get 'sources/new'
  get 'projects/new'
  get 'tags/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, except: [:new]
  resources :sources, except: [:new]
  resources :tags, except: [:new]
  resources :signs, except: [:show]
  resources :excerpts
end

app/models/excerpt.rb
class Excerpt < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_content,
                  against: [:content],
                  using: {
                      tsearch: { any_word: true }
                  }

  belongs_to :user
  belongs_to :source
  has_many :excerpt_tags, dependent: :destroy
  has_many :tags, through: :excerpt_tags

  validates :content, presence: true
  validates :source_id, presence: true
end

app/controllers/excerpts_controller.rb
class ExcerptsController < ApplicationController
  before_action :logged_in_user, only: [:create, :index]
  before_action :correct_user, only: [:edit, :show, :update, :destroy]

  def index
    if params.has_key?(:source_id)
      @search_result_excerpts = current_user.excerpts
      @search_result_excerpts = @search_result_excerpts.where(source_id: params[:source_id].to_i) if params[:source_id].present?

      if params[:tag_ids_any].count() > 1
        searchtagIds = params[:tag_ids_any].drop(1).map(&:to_i)
        list_of_excerpt_ids_with_the_tag = current_user.excerpt_tags.where(tag_id: searchtagIds).to_a.map{|x| x[:excerpt_id]}
        @search_result_excerpts = @search_result_excerpts.where(id: list_of_excerpt_ids_with_the_tag)
      end

      @search_result_excerpts = @search_result_excerpts.search_by_content(params[:text_content]) if params[:text_content].present?
      @search_result_excerpts = @search_result_excerpts.paginate(page: params[:page])

      respond_to do |format|
        format.js { render partial: 'search-results'}
      end
    else
      @excerpts = current_user.excerpts.paginate(page: params[:page])
    end
  end

  def new
    @excerpt = Excerpt.new
  end

  def destroy
    Excerpt.find(params[:id]).destroy
    flash[:success] = "Excerpt deleted"
    redirect_to excerpts_path
  end

  def edit
    @excerpt = Excerpt.find(params[:id])
  end

  def update
    @excerpt = Excerpt.find(params[:id])
    if @excerpt.update(excerpt_params)
      previousTagIds = ExcerptTag.where("excerpt_id = ?", @excerpt.id).to_a.map{|x| x[:tag_id]}
      currentTagIds = params[:excerpt][:tag_ids].drop(1).map(&:to_i)

      for tag in currentTagIds do
        if previousTagIds.exclude?(tag.to_i)
          @excerpt.excerpt_tags.create(user_id: current_user.id, excerpt_id: @excerpt.id, tag_id: tag.to_i)
        end
      end

      for tag in previousTagIds
        if currentTagIds.exclude?(tag.to_i)
          ExcerptTag.destroy_by(excerpt_id: @excerpt.id, tag_id: tag.to_i)
        end
      end

      flash[:success] = "Excerpt updated!"
      redirect_to excerpts_path
    end
  end

  def create
    @excerpt = current_user.excerpts.build(excerpt_params)
    if @excerpt.save
      # Add the excerpt tags
      if params[:excerpt][:tag_ids]
        for tag in params[:excerpt][:tag_ids] do
          @excerpt.excerpt_tags.create(user_id: current_user.id, excerpt_id: @excerpt.id, tag_id: tag)
        end
      end
      flash[:success] = "Excerpt created!"
      redirect_to excerpts_path
    else
      render 'static_pages/home'
    end
  end

  def show
    @excerpt = Excerpt.find(params[:id])
    @signExcerpts = Sign.where(source_id: params[:id]).paginate(page: params[:page])
  end

  private

  def excerpt_params
    params.require(:excerpt).permit(:source_id, :content, :location_reference, :tag_ids, :text_content, :tag_ids_any)
  end

  # Confirms the correct user.
  def correct_user
    @excerpt = current_user.excerpts.find_by(id: params[:id])
    redirect_to root_url if @excerpt.nil?
  end

end

app/helpers/excerpts_helper.rb
module ExcerptsHelper
  def user_has_excerpts
    current_user.excerpts.any?
  end
end

app/views/excerpts/_excerpt.html.erb
 <li class="d-flex justify-content-between align-items-center" id="excerpt-<%= excerpt.id%>">
    <div class="li-container">
      <div class="d-flex">
        <button class="btn btn-warning add-excerpt-to-sign add-excerpt-<%= excerpt.id%>" id="add-excerpt-<%= excerpt.id%>">Add this excerpt to your next sign</button>
        <button class="btn btn-danger remove-excerpt-from-sign no-show remove-excerpt-<%= excerpt.id%>" id="remove-excerpt-<%= excerpt.id%>">Remove this excerpt from your next sign</button>
        <button class="btn btn-danger remove-excerpt-from-within-form-modal no-show" id="remove-excerpt-within-<%= excerpt.id%>">Deselect</button>
      </div>
      <div>
        <span class="header">Content: </span>
        <span class="excerpt"><%= excerpt.content %></span>
      </div>
      <% if excerpt.location_reference %>
        <div>
          <span class="header">Location reference: </span>
          <span><%= number_with_precision(excerpt.location_reference, precision: 0)  %></span>
        </div>
      <% end %>
      <div>
        <span class="header">Source: </span>
        <span><%= link_to excerpt.source.title + " by " + excerpt.source.author, source_path(excerpt.source.id), title: "View only this source's excerpts" %></span>
      </div>
      <div>
        <span class="header">Creation date: </span>
        <span><%= time_tag excerpt.created_at  %></span>
      </div>
      <div>
        <span class="header">Last edition date: </span>
        <span><%= time_tag excerpt.updated_at  %></span>
      </div>
      <% if excerpt.excerpt_tags %>
        <div>
          <span class="header">Tags: </span>
          <% excerpt.excerpt_tags.each do |excerpt_tag| %>
            <span> #<%= link_to excerpt_tag.tag.title, tag_path(excerpt_tag.tag.id), title: "View excerpts tagged with this" %> </span>
            <% if(excerpt_tag != excerpt.excerpt_tags.last) %>
              ,
            <% end %>
          <%end %>
        </div>
      <% end %>
      <div class="excerpt-actions">
        <%= link_to "edit", edit_excerpt_path(excerpt.id) %> -
        <%= link_to "delete", excerpt, method: :delete, data: { confirm: "Please take into account that by deleting this excerpt you will lose created associations between this excerpt and signs of which it may be part of. Do you confirm?" } %>
      </div>
    </div>
  </li>

app/views/excerpts/_form.html.erb
<%= form_with(model: @excerpt, local: true) do |f| %>

  <% if @excerpt.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@excerpt.errors.count, "error") %>.
      </div>
      <ul>
        <% @excerpt.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :source_id %>
  <%= f.collection_select :source_id, current_user.sources.all, :id, :title, {}, class: 'selectize-add-source' %>

  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control' %>

  <%= f.label :location_reference %>
  <%= f.number_field :location_reference, class: 'form-control' %>

  <%= f.label :tag_ids, "Tags associated to this excerpt" %>
  <%= f.collection_select :tag_ids, current_user.tags.all, :id, :title, {}, multiple: true, class: 'selectize-add-tag' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/excerpts/_results.html.erb
<%= will_paginate @search_result_excerpts %>
<ul class="items">
  <%= render @search_result_excerpts %>
</ul>
<%= will_paginate @search_result_excerpts %>

app/views/excerpts/_search-results.js.erb
$("#all-excerpts").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/excerpts/edit.html.erb
<% provide(:title, 'Edit excerpt') %>
<% provide(:button_text, 'Save changes') %>
<h1>Edit excerpt</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/excerpts/index.erb
<% provide(:title, 'All excerpts') %>
<h1>Search excerpts</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with url: "/excerpts", method: "get" do |f|%>
      <%= f.label :source_id %>
      <%= f.collection_select :source_id, current_user.sources.all, :id, :title, {include_blank: 'All sources'}, class: 'selectize-search-single'%>

      <%= f.label :text_content, "Full text search against excerpt contents" %>
      <%= f.text_field :text_content, class: 'form-control', placeholder: 'E.g. slave classes revolutionary' %>

      <%= f.label :tag_ids_any, "Filter only from excerpts with any of the following tags:" %>
      <%= f.collection_select :tag_ids_any, current_user.tags.all, :id, :title, {prompt: 'Please start typing and select from existing tags'}, multiple: true, class: 'selectize-search-multiple' %>

      <%= submit_tag "Search", class: "btn btn-primary search-excerpts" %>
    <% end %>
  </div>
</div>

<div class="row top-buffer">
  <button class="btn btn-success pull-right" id="show-selected-excerpts">Show currently selected excerpts and add sign</button>
</div>

<div id="all-excerpts">
  <%= will_paginate %>
  <ul class="items">
    <%= render @excerpts %>
  </ul>
  <%= will_paginate %>
</div>

<div id="search-results">

</div>

<div class="modal fade show-selected-excerpts-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="mySmallModalLabel">Selected excerpts for your next sign</h4>
      </div>
      <div class="row center-aligned top-buffer">
        <a href='#' class="btn btn-primary create-sign-with-chosen-excerpts">Create a sign with these excerpts</a>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/excerpts/new.html.erb
<% provide(:title, 'Create new excerpts') %>
<h1>Add excerpt</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @excerpt, local: true) do |f| %>
      <% if @excerpt.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@excerpt.errors.count, "error") %>.
          </div>
          <ul>
            <% @excerpt.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label :source_id %>
      <%= f.collection_select :source_id, current_user.sources.all, :id, :title, {prompt: 'Please select or start typing and add a new source'}, class: 'selectize-add-source' %>

      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control', placeholder: 'E.g. Freeman and slave, patrician and plebeian, lord and serf, guildmaster and journeyman, in a word, oppressor and oppressed, stood in constant opposition to one another, carried on an uninterrupted, now hidden, now open fight, that each time ended, either in the revolutionary reconstitution of society at large, or in the common ruin of the contending classes.' %>

      <%= f.label :location_reference %>
      <%= f.number_field :location_reference, class: 'form-control', placeholder: "Page number or e-book position reference or leave blank if n/a" %>

      <%= f.label :tag_ids, "Tags associated to this excerpt" %>
      <%= f.collection_select :tag_ids, current_user.tags.all, :id, :title, {prompt: 'Please select from existing tags or start typing and add new ones'}, multiple: true, class: 'selectize-add-tag' %>

      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="modal fade tag-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="mySmallModalLabel">Add Tag</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%#= form_with(model: @tag, url: @tag, local: true, id: 'add-tag-form') do |f| %>
              <%# if @tag.errors.any? %>
<!--                <div id="error_explanation">-->
<!--                  <div class="alert alert-danger">-->
<!--                    The form contains <%#= pluralize(@tag.errors.count, "error") %>.-->
<!--                  </div>-->
<!--                  <ul>-->
                    <%# @tag.errors.full_messages.each do |msg| %>
<!--                      <li><%#= msg %></li>-->
                    <%# end %>
<!--                  </ul>-->
<!--                </div>-->
              <%# end %>
              <%= form_for Tag.new do |f| %>
              <%#= form_with(model: @tag, url: tags_create_path(@tag), local: true, id: 'add-tag-form') do |f| %>
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control', id: 'tag-title' %>

              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control', id: 'tag-description' %>

              <%= f.submit "Add", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade source-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="mySmallModalLabel">Add Source</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= form_for Source.new do |f| %>
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>

              <%= f.label :author, 'Author/s' %>
              <%= f.text_field :author, class: 'form-control' %>

              <%= f.label :url, 'External reference' %>
              <%= f.text_field :url, class: 'form-control', placeholder: 'E.g. The Wikipedia link for a book, or the original url for the source for a blog post, etc.' %>
              <%= f.submit "Add", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/excerpts/show.html.erb
<% provide(:title, 'Excerpt details') %>

<h1>Excerpt details</h1>
<div class="d-flex justify-content-between align-items-center">
  <div>
    <div>
      <span class="header">Content: </span>
      <span class="excerpt"><%= @excerpt.content %></span>
    </div>
    <% if @excerpt.location_reference %>
      <div>
        <span class="header">Location reference: </span>
        <span><%= number_with_precision(@excerpt.location_reference, precision: 0)  %></span>
      </div>
    <% end %>
    <div>
      <span class="header">Source: </span>
      <span><%= link_to @excerpt.source.title + " by " + @excerpt.source.author, source_path(@excerpt.source.id), title: "View only this source's excerpts" %></span>
    </div>
    <div>
      <span class="header">Creation date: </span>
      <span><%= time_tag @excerpt.created_at  %></span>
    </div>
    <div>
      <span class="header">Last edition date: </span>
      <span><%= time_tag @excerpt.updated_at  %></span>
    </div>
    <% if @excerpt.excerpt_tags %>
      <div>
        <span class="header">Tags: </span>
        <% @excerpt.excerpt_tags.each do |excerpt_tag| %>
          <span> #<%= link_to excerpt_tag.tag.title, tag_path(excerpt_tag.tag.id), title: "View excerpts tagged with this" %> </span>
          <% if(excerpt_tag != @excerpt.excerpt_tags.last) %>
            ,
          <% end %>
        <%end %>
      </div>
    <% end %>
  </div>
  <div>
    <%= link_to "edit", edit_excerpt_path(@excerpt.id) %> -
    <%= link_to "delete", @excerpt, method: :delete, data: { confirm: "Please take into account that by deleting this excerpt you will lose created associations between this excerpt and signs of which it may be part of. Do you confirm?" } %>
  </div>
</div>