config/routes.rb
Rails.application.routes.draw do
  get 'excerpts/new'
  get 'signs/new'
  get 'sources/new'
  get 'projects/new'
  get 'tags/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, except: [:new]
  resources :sources, except: [:new]
  resources :tags, except: [:new]
  resources :signs, except: [:show]
  resources :excerpts
end

app/models/sign.rb
class Sign < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_content,
                  against: [:content],
                  using: {
                      tsearch: { any_word: true }
                  }

  belongs_to :user
  belongs_to :project
  has_many :sign_excerpts
  has_many :excerpts, through: :sign_excerpts

  validates :content, presence: true
  validates :project_id, presence: true
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  before_action :logged_in_user, only: [:create, :index]
  before_action :correct_user, only: [:edit, :show, :update, :destroy]

  def index
    if params.has_key?(:project_id)

      @search_result_signs = current_user.signs
      @search_result_signs = @search_result_signs.where(project_id: params[:project_id].to_i) if params[:project_id].present?

      if params[:tag_ids_any].count() > 1
        seachtagIds = params[:tag_ids_any].drop(1).map(&:to_i)
        list_of_excerpt_ids_with_the_tag = current_user.excerpt_tags.where(tag_id: seachtagIds).to_a.map{|x| x[:excerpt_id]}
        list_of_signs_with_excerpts_with_the_tags = current_user.sign_excerpts.where(excerpt_id: list_of_excerpt_ids_with_the_tag).to_a.map{|x| x[:sign_id]}
        @search_result_signs = @search_result_signs.where(id: list_of_signs_with_excerpts_with_the_tags)
      end

      @search_result_signs = @search_result_signs.search_by_content(params[:text_content]) if params[:text_content].present?
      @search_result_signs = @search_result_signs.paginate(page: params[:page])

      respond_to do |format|
        format.js { render partial: 'search-results'}
      end
    else
      @signs = current_user.signs.paginate(page: params[:page])
    end
  end

  def new
    @sign = Sign.new
    @excerpts_ids = params[:excerpt_ids]
  end

  def destroy
    Sign.find(params[:id]).destroy
    flash[:success] = "Sign deleted"
    redirect_to signs_path
  end

  def edit
    @sign = Sign.find(params[:id])
  end

  def show
    @excerpt = Excerpt.find(params[:id])
    list_of_sign_ids_with_the_excerpt = SignExcerpt.where(excerpt_id: params[:id]).to_a.map{|x| x[:sign_id]}
    @signsWithExcerpt = Sign.where(id: list_of_sign_ids_with_the_excerpt).paginate(page: params[:page])
  end

  def update
    @sign = Sign.find(params[:id])
    if @sign.update(sign_params)
      previousExcerptIds = SignExcerpt.where("sign_id = ?", @sign.id).to_a.map{|x| x[:excerpt_id]}
      currentExcerptIds = params[:sign][:excerpt_ids].drop(1).map(&:to_i)

        for excerpt in currentExcerptIds do
          if previousExcerptIds.exclude?(excerpt.to_i)
            @sign.sign_excerpts.create(user_id: current_user.id, sign_id: @sign.id, excerpt_id: excerpt.to_i)
          end
        end

        for excerpt in previousExcerptIds
          if currentExcerptIds.exclude?(excerpt.to_i)
            SignExcerpt.destroy_by(sign_id: @sign.id, excerpt_id: excerpt.to_i)
          end
        end

      flash[:success] = "Sign updated!"
      redirect_to signs_path
    end
  end

  def create
    @sign = current_user.signs.build(sign_params)
    if @sign.save
      # Add the excerpts
      if params[:sign][:excerpt_ids]
        for excerpt in params[:sign][:excerpt_ids] do
          @sign.sign_excerpts.create(user_id: current_user.id, sign_id: @sign.id, excerpt_id: excerpt)
        end
      end
      flash[:success] = "Sign created!"
      redirect_to signs_path
    else
      render 'static_pages/home'
    end
  end

  private

  def sign_params
    params.require(:sign).permit(:project_id, :content, :tag_ids_any, :text_content, :excerpt_ids)
  end

  # Confirms the correct user.
  def correct_user
    @sign = current_user.signs.find_by(id: params[:id])
    redirect_to root_url if @sign.nil?
  end

end

app/helpers/signs_helper.rb
module SignsHelper
  def user_has_signs
    current_user.signs.any?
  end
end

app/views/signs/_form.html.erb
<%= form_with(model: @sign, local: true) do |f| %>

  <% if @sign.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@sign.errors.count, "error") %>.
      </div>
      <ul>
        <% @sign.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :project_id, 'Project' %>
  <%= f.collection_select :project_id, current_user.projects.all, :id, :title, {}, class: 'selectize-add-project' %>

  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control' %>

  <%= f.label :excerpt_ids, 'Distilled from the following excerpts:' %>
  <%= f.collection_select :excerpt_ids, current_user.excerpts.all, :id, :content, {}, multiple: true, class: 'selectize-search-multiple' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/signs/_results.html.erb
<%= will_paginate @search_result_signs %>
<%= link_to "Create new", signs_new_path , class: "btn btn-primary pull-right"%>
<ul class="items">
  <%= render @search_result_signs %>
</ul>
<%= will_paginate @search_result_signs %>

app/views/signs/_search-results.js.erb
$("#all-signs").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/signs/_sign.html.erb
 <li class="d-flex justify-content-between align-items-center">
  <div>
    <div>
      <span class="header">Content: </span>
      <span class="excerpt"><%= sign.content %></span>
    </div>
    <div>
      <span class="header">Creation date: </span>
      <span><%= time_tag sign.created_at  %></span>
    </div>
    <div>
      <span class="header">Last edition date: </span>
      <span><%= time_tag sign.updated_at  %></span>
    </div>
    <div>
      <span class="header">Project: </span>
      <span><%= link_to sign.project.title, project_path(sign.project.id), title: "View only this project's signs" %></span>
    </div>

      <div>
        <span class="header">Extracted from the following excerpts: </span>
        <% sign.sign_excerpts.each do |sign_excerpt| %>
          <div> <%= link_to sign_excerpt.excerpt.content.first(100) + '...', excerpt_path(sign_excerpt.excerpt.id), title: "View excerpt details" %> </div>
        <%end %>
      </div>

  </div>
  <div>
    <%= link_to "edit", edit_sign_path(sign.id) %> -
    <%= link_to "delete", sign, method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</li>

app/views/signs/edit.html.erb
<% provide(:title, 'Edit sign') %>
<% provide(:button_text, 'Save changes') %>
<h1>Edit your sign</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/signs/index.erb
<% provide(:title, 'All signs') %>
<h1>Search signs</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with url: "/signs", method: "get" do |f|%>
      <%= f.label :project_id %>
      <%= f.collection_select :project_id, current_user.projects.all, :id, :title, {include_blank: 'All projects'}, class: 'selectize-search-single' %>
      <%= f.label :text_content, "Full text search against sign contents" %>
      <%= f.text_field :text_content, class: 'form-control', placeholder: 'E.g. slave classes revolutionary' %>

      <%= f.label :tag_ids_any, "Filter only from signs made with excerpts that have any of the following tags:" %>
      <%= f.collection_select :tag_ids_any, current_user.tags.all, :id, :title, {prompt: 'Please start typing and select from existing tags'}, multiple: true, class: 'selectize-search-multiple' %>

      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div id="all-signs">
  <%= will_paginate %>
  <ul class="items">
    <%= render @signs %>
  </ul>
  <%= will_paginate %>
</div>

<div id="search-results">

</div>

app/views/signs/new.html.erb
<% provide(:title, 'Create new signs') %>
<h1>Create sign</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @sign, local: true) do |f| %>
      <% if @sign.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            The form contains <%= pluralize(@sign.errors.count, "error") %>.
          </div>
          <ul>
            <% @sign.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label :project_id %>
      <%= f.collection_select :project_id, current_user.projects.all, :id, :title, {prompt: 'Please select or start typing and add a new project'}, class: 'selectize-add-project' %>

      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control', placeholder: 'This is where you put your comment extracted from a chosen selection of excerpts.' %>

      <% unless params[:excerpt_ids] %>
      <%= f.label :excerpt_ids, 'Distilled from the following excerpts:' %>
      <%= f.collection_select :excerpt_ids, current_user.excerpts.all, :id, :content, {}, multiple: true, class: 'selectize-search-multiple' %>
      <% else %>
        <%#= params[:excerpt_ids] %>
        <% params[:excerpt_ids].each do |excerpt_id| %>
          <%= f.hidden_field :excerpt_ids, :multiple => true, :value => excerpt_id %>
        <% end %>
      <% end %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="modal fade project-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="mySmallModalLabel">Add Project</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= form_for Project.new do |f| %>
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>

              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control', placeholder: "E.g: Piece about the influence of marxist ideas on sci-fi literature" %>

              <%= f.submit "Add", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/signs/show.html.erb
<% provide(:title, 'Signs associated to this excerpt') %>
<h1>Signs distilled from:</h1>
<div><%= @excerpt.content %></div>

<%= will_paginate @signsWithExcerpt %>
<ul class="items">
  <%= render @signsWithExcerpt %>
</ul>
<%= will_paginate @signsWithExcerpt %>