config/routes.rb
Rails.application.routes.draw do
  get 'excerpts/new'
  get 'signs/new'
  get 'sources/new'
  get 'projects/new'
  get 'tags/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :projects, except: [:new]
  resources :sources, except: [:new]
  resources :tags, except: [:new]
  resources :signs, except: [:show]
  resources :excerpts
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Skiltr
    by <a href="https://www.linkedin.com/in/nicolasgkruk/">Nicolás Kruk</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "skiltr", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse"
          id="bs-example-navbar-collapse-1">
        <% if logged_in? %>
          <li><%= link_to "Guide", help_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Add new... <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Excerpt", excerpts_new_path %></li>
              <li><%= link_to "Sign", signs_new_path %></li>
            </ul>
          </li>

          <% if user_has_signs || user_has_excerpts %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Search <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if user_has_excerpts %>
              <li><%= link_to "Excerpts", excerpts_path %></li>
              <% end %>
              <% if user_has_signs %>
              <li><%= link_to "Signs", signs_path %></li>
              <% end %>
            </ul>
          </li>
          <% end %>

          <% if user_has_projects || user_has_sources || user_has_tags %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                View all <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if user_has_projects %>
                  <li><%= link_to "Projects", projects_path %></li>
                <% end %>
                <% if user_has_tags %>
                  <li><%= link_to "Tags", tags_path %></li>
                <% end %>
                <% if user_has_sources %>
                  <li><%= link_to "Sources", sources_path %></li>
                <% end %>
              </ul>
            </li>
          <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>